#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
#          curl http://100.26.133.196/   --> returns string "Hello World!"
#          curl http://100.26.133.196/   --> returns header info

apt-get -y update
apt-get -y install nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

printf "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
}" > /etc/nginx/sites-available/default

service nginx restart
