#!/usr/bin/env bash

# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
#          curl http://100.26.133.196/   --> returns string "Hello World!"
#          curl http://100.26.133.196/   --> returns header info

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | tee /usr/share/nginx/html/index.html
service nginx start