#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that
# contains a string of your choosing

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

echo "Printing into file now"

printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    add_header X-Served-By $HOSTNAME;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
      return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart

