#!/usr/bin/env bash
# a bash script to find out what’s keeping the Ubuntu container’s Nginx
# installation from listening on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
